/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package idao;

import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ABDELLAH DIDI
 */
public class GestionPlanning extends javax.swing.JFrame {

    String date="";
    String time="";
    Dashboard D=null;
    
     private static final Color BLUE_COLOR = new Color(100, 100, 255);
    private static final Color RED_COLOR = new Color(255, 100, 100); // Red color for highlighting
    /**
     * Creates new form GestionPlanning
     */
    public GestionPlanning() {
        initComponents();
        load();
       load_list();
       load_site();
       load_departement();
       HtimeL.setMaximum(23);
       HtimeL.setMinimum(0);
       Htime_C.setMaximum(23);
       Htime_C.setMinimum(0);
       Mtime_L.setMaximum(59);
       Mtime_L.setMinimum(0);
       Mtime_C.setMaximum(59);
       Mtime_C.setMinimum(0);
    }

       public GestionPlanning(Dashboard D,String a,String b) {
        initComponents();

        this.D=D;
        date=a;
        time=b;
                load();
                load_list();
                       load_site();
       load_departement();
       HtimeL.setMaximum(23);
       HtimeL.setMinimum(0);
       Htime_C.setMaximum(23);
       Htime_C.setMinimum(0);
       Mtime_L.setMaximum(59);
       Mtime_L.setMinimum(0);
       Mtime_C.setMaximum(59);
       Mtime_C.setMinimum(0);
    }
       
           private void load_list(){
            iutilisateur a = new iutilisateur();
            CheckList c = new CheckList();
         
             Iterator<utilisateur> it =    a.lister().iterator() ;
     
          while(it.hasNext()){
              utilisateur  var = it.next();
        tAuditeur.addItem(var.getMatricule()+" : "+ var.getNom()+" "+var.getPrenom() );
             // System.out.println("Auditeur : "+var.getNom()+" "+var.getPrenom()+"\n");
   
        }
         Iterator<CheckList>  it1 =    c.lister().iterator() ;
          
          while(it1.hasNext()){
              CheckList  var = it1.next();
        tCheck.addItem(var.getDescription() );
        }
           }
           

    
    void load(){
        
        Object [][]  data = new Object[0][0]; 
        
       CustomAuditTableModel x =   new CustomAuditTableModel(data,true);//Planning
    
       x.copy((new iaudit()).ToResultSetPlanning(date));
       tabPlanning.setModel( x);
    
    }
    void load(String a,String b ){
        
        Object [][]  data = new Object[0][0]; 
        
       CustomAuditTableModel x =   new CustomAuditTableModel(data,true);//Planning
    
       x.copy((new iaudit()).ToResultSetPlanning(date,a,b));
       tabPlanning.setModel( x);
    
    }
    void load_site(){
         Site s = new Site();
         
             Iterator<Site> it =    s.lister().iterator() ;
             
     tsite.addItem(" ");
          while(it.hasNext())  tsite.addItem(it.next().toString());
    }
    void load_departement(){
         iutilisateur s = new iutilisateur();
         
             Iterator<String> it =   s.lister_departement().iterator();
     tdpartement.addItem(" ");
          while(it.hasNext())  tdpartement.addItem(it.next());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Supprimer = new javax.swing.JButton();
        ModifierAudit = new javax.swing.JButton();
        CreerAudit1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPlanning =  new JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);

                if (!isRowSelected(row)) {
                    Date currentDate = new Date(); // Get the current date
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                    // Get the "Date Limite" value from the table model (assuming it's in column index 4)
                    Object dateLimiteValue = getModel().getValueAt(row, 3);

                    if (dateLimiteValue instanceof String) {
                        try {
                            Date dateLimite = dateFormat.parse((String) dateLimiteValue);

                            if (dateLimite.before(currentDate)) {
                                component.setBackground(RED_COLOR);
                            } else {
                                component.setBackground(BLUE_COLOR);
                            }
                        } catch (java.text.ParseException ex) {
                            // Handle parsing exception if needed
                        }
                    } else {
                        component.setBackground(getBackground());
                    }
                }

                return component;
            }
        };
        tsite = new javax.swing.JComboBox<>();
        tdpartement = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Rénititialer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tCheck = new javax.swing.JComboBox<>();
        tAuditeur = new javax.swing.JComboBox<>();
        tCreation = new com.toedter.calendar.JDateChooser();
        tLimite = new com.toedter.calendar.JDateChooser();
        Htime_C = new com.toedter.components.JSpinField();
        Mtime_C = new com.toedter.components.JSpinField();
        HtimeL = new com.toedter.components.JSpinField();
        Mtime_L = new com.toedter.components.JSpinField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        Executer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion des planning ");
        setIconImage(  (new ImageIcon("./img/COFICAB.jpeg")).getImage()

        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(962, 127));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Listes des Audits Planifiés");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(767, 618));

        jPanel3.setMaximumSize(new java.awt.Dimension(767, 570));
        jPanel3.setMinimumSize(new java.awt.Dimension(767, 570));

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        ModifierAudit.setText("MODIFIER");
        ModifierAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierAuditActionPerformed(evt);
            }
        });

        CreerAudit1.setText("CREER");
        CreerAudit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerAudit1ActionPerformed(evt);
            }
        });

        tabPlanning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabPlanning);

        tsite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tsiteItemStateChanged(evt);
            }
        });

        tdpartement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tdpartementItemStateChanged(evt);
            }
        });

        jLabel10.setText("Departement ");

        jLabel11.setText("Site");

        Rénititialer.setText("Rénititialer");
        Rénititialer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RénititialerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(ModifierAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Rénititialer)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(tsite, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tdpartement, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(CreerAudit1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(791, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdpartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Rénititialer, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(605, Short.MAX_VALUE)
                    .addComponent(CreerAudit1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(581, 587));
        jPanel4.setMinimumSize(new java.awt.Dimension(581, 587));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Auditeur ");

        jLabel3.setText("Check List ");

        jLabel4.setText("Date limite ");

        jLabel5.setText("Date de création");

        jLabel6.setText("h");

        jLabel7.setText("min");

        jLabel8.setText("h");

        jLabel9.setText("min");

        Retour.setText("RETOUR");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Executer1.setText("Ajouter");
        Executer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Executer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tAuditeur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tCheck, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tCreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(Htime_C, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(Mtime_C, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(HtimeL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mtime_L, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Executer1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(34, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tAuditeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Mtime_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Htime_C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HtimeL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mtime_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Executer1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 624, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        D.setEnabled(true);
           this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:

        int row = tabPlanning.getSelectedRow();
        if(row != -1) {
            (new iaudit()).delete(new Audit(Integer.parseInt(tabPlanning.getValueAt(row, -1).toString())));
            load();
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void CreerAudit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerAudit1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
           Executer1.setText("Ajouter");
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         try {
            Date date1 = sdf.parse(date);
            System.out.println("Parsed date1 : " + date1);
               tCreation.setDate(date1);
        } catch (ParseException e) {
            e.getMessage();
        }
         
         
         Date now = new Date();
                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
         time = timeFormat.format(now.getTime());
         
         //HH:mm:ss
         String [] a = time.split(":");
         Htime_C.setValue(Integer.parseInt(a[0]));
         Mtime_C.setValue(Integer.parseInt(a[1]));
     
    }//GEN-LAST:event_CreerAudit1ActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(0);
            
    }//GEN-LAST:event_RetourActionPerformed

    private void Executer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Executer1ActionPerformed
        // TODO add your handling code here:
                
        if(tLimite.getDate()!=null && tCreation.getDate()!=null){
         int result = tLimite.getDate().compareTo(tCreation.getDate());
            if( result < 0  ){
                JOptionPane.showMessageDialog(null, "la date limite est inférieur à la date de création !!!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            }else{
               
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         
             
        String limite = dateFormat.format(tLimite.getDate())+" "+HtimeL.getValue()+":"+Mtime_L.getValue()+":00";
        String creation = dateFormat.format(tCreation.getDate())+" "+Htime_C.getValue()+":"+Mtime_C.getValue()+":00";
        
                System.out.println("limite : "+limite+"\n");
     
        
        
        
                   String[] substrings = tAuditeur.getSelectedItem().toString().split(" ");
                  
                 CheckList c=  new CheckList(tCheck.getSelectedItem().toString());
                 c.setId(c.getId_Planning());
               
                    if(Executer1.getText() == "Ajouter")
                    {
                          (new iaudit()).add_Planning(new Audit(  substrings[0] ,  
                              
                              c
                              ,creation,
                              limite ));
                       JOptionPane.showMessageDialog(null, "Vous avez bien créer un nouveau audit !!!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
                    
                    }
                    else 
                    {
                          (new iaudit()).update_Planning(new Audit(  substrings[0] ,  
                              
                              c
                              ,creation,
                              limite, Integer.parseInt(tabPlanning.getValueAt(tabPlanning.getSelectedRow(), -1).toString() ))
                                  
                          
                          );
                       JOptionPane.showMessageDialog(null, "Vous avez bien modifié un audit !!!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
                    
                    }
                    
                       
                                     jTabbedPane1.setSelectedIndex(0);
                                     load();
                       
            }
        }
    }//GEN-LAST:event_Executer1ActionPerformed

    private void ModifierAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierAuditActionPerformed
        // TODO add your handling code here:
              int row = tabPlanning.getSelectedRow();
        if(row != -1) {
           System.out.println("tabPlanning.getValueAt(tabPlanning.getSelectedRow(), -1).toString() : "+tabPlanning.getValueAt(tabPlanning.getSelectedRow(), -1).toString()+"\n");

           jTabbedPane1.setSelectedIndex(1);
           Executer1.setText("Modifier");
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          Date date1;
                  try {
                      date1 = sdf.parse(split(tabPlanning.getValueAt(row, 2).toString(),"date", -1 ));
                                System.out.println("Parsed date1 : " + date1);
          tCreation.setDate(date1);
                    date1 = sdf.parse(split(tabPlanning.getValueAt(row, 3).toString(),"date", -1 ));
                                System.out.println("Parsed date2 : " + date1);
                                      tLimite.setDate(date1);
                  } catch (ParseException ex) {
                      Logger.getLogger(GestionPlanning.class.getName()).log(Level.SEVERE, null, ex);
                  }

         Htime_C.setValue(Integer.parseInt(split(tabPlanning.getValueAt(row, 2).toString(),"time",0 )));
         Mtime_C.setValue(Integer.parseInt(split(tabPlanning.getValueAt(row, 2).toString(),"time",1)));  
         HtimeL.setValue(Integer.parseInt(split(tabPlanning.getValueAt(row, 3).toString(),"time",0 )));
         Mtime_L.setValue(Integer.parseInt(split(tabPlanning.getValueAt(row, 3).toString(),"time",1)));  
         
         utilisateur u =new utilisateur(tabPlanning.getValueAt(row, 0).toString());
                
            tAuditeur.setSelectedItem(u.getMatricule()+" : "+ new iutilisateur().set_nom_prenom(u) );
            
            System.out.println("Auditeur : "+u.getMatricule()+" : "+u.getNom()+" "+u.getPrenom()+"\n");
            
          CheckList c= new CheckList(tabPlanning.getValueAt(row, 1).toString());
          c.getId_Planning();
          tCheck.setSelectedItem(c.getDescription());
          
            
            
        }
        
    }//GEN-LAST:event_ModifierAuditActionPerformed

    private void tsiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tsiteItemStateChanged
        // TODO add your handling code here:
        
             if( tsite.getSelectedItem() != null &&   tdpartement.getSelectedItem()!= null ){
            if(!" ".equals(tsite.getSelectedItem().toString()) || !" ".equals(tdpartement.getSelectedItem().toString()))
                 load(tsite.getSelectedItem().toString() , tdpartement.getSelectedItem().toString() );
            
       }
       else   if( tsite.getSelectedItem() != null ){
              if(!" ".equals(tsite.getSelectedItem().toString()) )
                  load(tsite.getSelectedItem().toString()," " );
       }
       else if(    tdpartement.getSelectedItem()!= null ) {
            if(!" ".equals(tdpartement.getSelectedItem().toString()))
                         load(" ", tdpartement.getSelectedItem().toString() );
       }
     
        
        
    }//GEN-LAST:event_tsiteItemStateChanged

    private void tdpartementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tdpartementItemStateChanged
        // TODO add your handling code here:

       if( tsite.getSelectedItem() != null &&   tdpartement.getSelectedItem()!= null ){
            if(!" ".equals(tsite.getSelectedItem().toString()) || !" ".equals(tdpartement.getSelectedItem().toString()))
                 load(tsite.getSelectedItem().toString() , tdpartement.getSelectedItem().toString() );
            
       }
       else   if( tsite.getSelectedItem() != null ){
              if(!" ".equals(tsite.getSelectedItem().toString()) )
                  load(tsite.getSelectedItem().toString()," " );
       }
       else if(    tdpartement.getSelectedItem()!= null ) {
            if(!" ".equals(tdpartement.getSelectedItem().toString()))
                         load(" ", tdpartement.getSelectedItem().toString() );
       }
     
     
     
     
   
        
    }//GEN-LAST:event_tdpartementItemStateChanged

    private void RénititialerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RénititialerActionPerformed
        // TODO add your handling code here:
      load();
       load_list();
   tsite.setSelectedIndex(0);
   tdpartement.setSelectedIndex(0);
    }//GEN-LAST:event_RénititialerActionPerformed

    String split(String a,String c, int i){
        
        String[]  b=a.split(" ");
        String [] Sdate=b[0].split(":");
        String [] Stime=b[1].split(":");
        if(c=="date" && i> -1)
                    return Sdate[i];
        if(c=="time" && i> -1 )
                    return Stime[i];
        if(c=="date" && i ==-1)
                    return b[0];
        if(c=="time"  && i ==-2)
                    return b[1];
        return "";
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GestionPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GestionPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GestionPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GestionPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GestionPlanning().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreerAudit1;
    private javax.swing.JButton Executer1;
    private com.toedter.components.JSpinField HtimeL;
    private com.toedter.components.JSpinField Htime_C;
    private javax.swing.JButton ModifierAudit;
    private com.toedter.components.JSpinField Mtime_C;
    private com.toedter.components.JSpinField Mtime_L;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Rénititialer;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> tAuditeur;
    private javax.swing.JComboBox<String> tCheck;
    private com.toedter.calendar.JDateChooser tCreation;
    private com.toedter.calendar.JDateChooser tLimite;
    private javax.swing.JTable tabPlanning;
    private javax.swing.JComboBox<String> tdpartement;
    private javax.swing.JComboBox<String> tsite;
    // End of variables declaration//GEN-END:variables
}
